#include<iostream>
using namespace std;
void digitToText(int n1);
main()
{
cout<<"Enter a number: ";
     int number;
     cin>>number;
     digitToText(number);

}
void digitToText(int n1)
{     if (n1 == 1)
{
    cout<<"One";
}
     if(n1==2)
     {
        cout<<"Two";
     }
      if(n1==3)
     {
        cout<<"Three";
}
       if(n1==4)
     {
        cout<<"Four";
}
 if(n1==5)
     {
        cout<<"Five";
     }
 if(n1==6)
     {
        cout<<"Six";}
 if(n1==7)
     {
        cout<<"Seven";
}
 if(n1==8)
     {
        cout<<"Eight";
     }
      if(n1==9)
     {
        cout<<"Nine";
     }
      if(n1==10)
     {
        cout<<"Ten";}
      if(n1==11)
     {
        cout<<"Eleven";
     }
 if(n1==12)
     {
        cout<<"Twelve";
     }
      if(n1==13)
     {
        cout<<"Thirteen";
     }
      if(n1==14)
     {
        cout<<"Fourteen";
     }
      if(n1==15)
     {
        cout<<"Fifteen";
     }
      if(n1==16)
     {
        cout<<"Sixteen";
     }
      if(n1==17)
     {
        cout<<"Seventeen";
     }
      if(n1==18)
     {
        cout<<"Eighteen";
     }
      if(n1==19)
     {
        cout<<"Ninteen";
     }
      if(n1==20)
     {
        cout<<"Twenty";
     }
      if(n1==21)
     {
        cout<<"TwentyOne";
     }
      if(n1==22)
     {
        cout<<"TwentyTwo";  }
         if(n1==23)
     {
        cout<<"TwentyThree";
     }
      if(n1==24)
     {
        cout<<"Two";  }
         if(n1==25)
     {
        cout<<"TwentyFive";
     }
      if(n1==26)
     {
        cout<<"TwentySix";
     }
      if(n1==27)
     {
        cout<<"TwentySeven";
     }
      if(n1==28)
     {
        cout<<"TwentyEight";   }
         if(n1==29)
     {
        cout<<"TwentyNine";
     }
      if(n1==30)
     {
        cout<<"Thirty";}
         if(n1==31)
     {
        cout<<"ThirtyOne";}
         if(n1==32)
     {
        cout<<"ThirtyTwo";}
         if(n1==33)
     {
        cout<<"ThirtyThree";}
         if(n1==34)
     {
        cout<<"ThirtyFour";}
         if(n1==35)
     {
        cout<<"ThirtyFive";}
         if(n1==36)
     {
        cout<<"ThirtySix";}
         if(n1==37)
     {
        cout<<"ThirtySeven";}
         if(n1==38)
     {
        cout<<"ThirtyEight";}
         if(n1==39)
     {
        cout<<"ThirtyNine";}
         if(n1==40)
     {
        cout<<"Forty";}
        if(n1==41)
     {
        cout<<"FortyOne";}
        if(n1==42)
     {
        cout<<"FortyTwo";}
        if(n1==43)
     {
        cout<<"FortyThree";}
        if(n1==44)
     {
        cout<<"FortyFour";}
        if(n1==45)
     {
        cout<<"FortyFive";}
        if(n1==46)
     {
        cout<<"FortySix";}
        if(n1==47)
     {
        cout<<"FortySeven";}
        if(n1==48)
     {
        cout<<"FortyEight";}
        if(n1==49)
     {
        cout<<"FortyNine";}
        if(n1==50)
     {
        cout<<"Fifty";}
        if(n1==51)
     {
        cout<<"FiftyOne";}
        if(n1==52)
     {
        cout<<"FiftyTwo";}
        if(n1==53)
     {
        cout<<"FiftyThree";}
        if(n1==54)
     {
        cout<<"FiftyFour";}
        if(n1==55)
     {
        cout<<"FiftyFive";}
        if(n1==56)
     {
        cout<<"FiftySix";}
        if(n1==57)
     {
        cout<<"FiftySeven";}
        if(n1==58)
     {
        cout<<"FiftyEight";}
        if(n1==59)
     {
        cout<<"FiftyNine";}
        if(n1==60)
     {
        cout<<"Sixty";}
        if(n1==61)
     {
        cout<<"SixtyOne";}
        if(n1==62)
     {
        cout<<"SixtyTwo";}
        if(n1==63)
     {
        cout<<"SixtyThree";}
        if(n1==64)
     {
        cout<<"SixtyFour";}
        if(n1==65)
     {
        cout<<"SixtyFive";}
        if(n1==66)
     {
        cout<<"SixtySix";}
        if(n1==67)
     {
        cout<<"SixtySeven";}
        if(n1==68)
     {
        cout<<"SixtyEight";}
        if(n1==69)
     {
        cout<<"SixtyNine";}
        if(n1==70)
     {
        cout<<"Seventy";}
        if(n1==71)
     {
        cout<<"SeventyOne";}
        if(n1==72)
     {
        cout<<"SeventyTwo";}
        if(n1==73)
     {
        cout<<"SeventyThree";}
        if(n1==74)
     {
        cout<<"SeventyFour";}
        if(n1==75)
     {
        cout<<"SeventyFive";}
        if(n1==76)
     {
        cout<<"SeventySix";}
        if(n1==77)
     {
        cout<<"SeventySeven";}
        if(n1==78)
     {
        cout<<"SeventyEight";}
        if(n1==79)
     {
        cout<<"SeventyNine";}
        if(n1==80)
     {
        cout<<"Eighty";}
        if(n1==81)
     {
        cout<<"EightyOne";}
         if(n1==82)
     {
        cout<<"EightyTwo";}
         if(n1==83)
     {
        cout<<"EightyThree";}
         if(n1==84)
     {
        cout<<"EightyFour";}
         if(n1==85)
     {
        cout<<"EightyFive";}
         if(n1==86)
     {
        cout<<"EightySix";}
         if(n1==87)
     {
        cout<<"EightySeven";}
         if(n1==88)
     {
        cout<<"EightyEight";}
         if(n1==89)
     {
        cout<<"EightyNine";}
         if(n1==90)
     {
        cout<<"Ninty";}
         if(n1==91)
     {
        cout<<"NintyOne";}
         if(n1==92)
     {
        cout<<"NintyTwo";}
         if(n1==93)
     {
        cout<<"NintyThree";}
         if(n1==94)
     {
        cout<<"NintyFour";}
         if(n1==95)
     {
        cout<<"NintyFive";}
         if(n1==96)
     {
        cout<<"NintySix";}
         if(n1==97)
     {
        cout<<"NintySeven";}
         if(n1==98)
     {
        cout<<"NintyEight";}
         if(n1==99)
     {
        cout<<"NintyNine";}
}
        
        

















      